version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn eld_trip_planner.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend/eld-trip-planner/
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://backend:8000"
    ports:
      - "80:80"
    restart: always
