from django.conf import settings

OSRM_ROUTE_URL = getattr(settings, "OSRM_ROUTE_URL")
NOMINATIM_URL = getattr(settings, "NOMINATIM_URL")
EARTH_RADIUS_M = 6371000
FUEL_INTERVAL_M = 1609344  # ~1000 miles (meters)
METERS_TO_MILES = 0.000621371

# 70/8 cycle info
MAX_CYCLE_HOURS = 70.0
MAX_CYCLE_DAYS = 8.0

# Day standards
MAX_DRIVING_HOURS_PER_DAY = 11.0
MAX_DRIVING_HOURS_TO_REST = 8.0
END_OF_DAY_REST_DURATION_H = 10.0
BREAK_DURATION_H = 0.5

# On duty activities
PICKUP_DURATION_H = 1.0
DROPOFF_DURATION_H = 1.0
TRIP_TIV_DURATION_H = 0.5

# Time info
SECONDS_TO_HOURS = 3600.0
HOURS_IN_DAY = 24.0
NUMBER_OF_HOURS_FROM_MIDNIGHT_TO_SIX = 6
